CREATE DATABASE exam
GO

USE exam
GO

CREATE TABLE [Product]
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(100)
)

CREATE TABLE Customer
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(100)
)

CREATE TABLE Orders1 
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Quantity INT,
	Order_date DATE,
	Price DECIMAL(10,2),
	Customer_id UNIQUEIDENTIFIER,
	Product_id UNIQUEIDENTIFIER
	FOREIGN KEY(Customer_id) REFERENCES Customer(Id),
	FOREIGN KEY(Product_id) REFERENCES [Product](Id)
)
