CREATE DATABASE Variant5
GO

USE Variant5
GO

CREATE TABLE [Status]
(
	[Name] NVARCHAR(50) PRIMARY KEY
)

CREATE TABLE Customer
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE [Order]
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Order_date DATE NOT NULL,
	Payment_method NVARCHAR(20) NOT NULL,
	Status_id NVARCHAR(50) NOT NULL,
	Customer_id UNIQUEIDENTIFIER NOT NULL

	FOREIGN KEY(Status_id) REFERENCES [Status]([Name]),
	FOREIGN KEY(Customer_id) REFERENCES Customer(Id)
)
